[package]
name = "elliptic"
version = "0.4.0"
authors = ["Jihyeok Seo <limeburst@member.fsf.org>"]
description = "Rust bindings for agl/curve25519-donna and trevp/ref10_extract."
repository = "https://github.com/lumi-im/elliptic"
license = "CC0-1.0"

[dependencies]
elliptic-sys = "0.2.0"
